### ISSUE TITLE
Feature request: const fn new

### ISSUE THREAD

**Issue by kstrafe** [bluurryy/bump-scope#7]
Making Bump::new be const fn allows for use in thread locals via 
```
thread_local! {
    static X: Bump = const { Bump::new() };
}
```

This makes thread local access much faster because we do not need to perform a dynamic check for each access to the thread local.

**Comment by bluurryy** [comment]
If we implemented `new` like bumpalo using their `EMPTY_CHUNK` trick, we could make it `const` in nightly with `#![feature(const_refs_to_static)]`.

The thing is that we have a doubly linked list of chunks instead of singly linked list. This is so we can reuse and don't have to deallocate chunks that we allocated in a scope.

We would have to check every time we create a new scope or checkpoint if we are pointing to that `EMPTY_CHUNK` and if so allocate a real chunk that we can mutate and link up with future chunks.

**Comment by bluurryy** [comment]
Bump allocators can now be constructed without allocation via `Bump::uninit`. This only works with the `Global` allocator.
It's const when the feature `nightly-const-refs-to-static` is enabled.

```rust
type Bump = bump_scope::Bump<Global, 1, true, false>;

thread_local! {
    static BUMP: Bump = const { Bump::uninit() };
}
```
An uninitialized bump allocator can't create scopes or checkpoints, but everything else works.
You can initialize an uninitialized bump allocator with `into_init` or `as_init(_mut)`.
